### ISSUE TITLE
Completing an action returns 405

### ISSUE THREAD

**Issue by ThePerryR** [hypertrack/hypertrack-node-sdk#2]
When calling `hypertrack.actions.complete` the response is a 405 with data:  { detail: 'Method "GET" not allowed.' }

Unlike the issue with users.assignAction, actions.complete is using this.request.post.

**Comment by rishabhgrg** [comment]
@ThePerryR Its fixed with the latest release(2.2.0). It happened because the trailing slash was missing which caused GET redirect for POST.
